CREATE PROCEDURE [adi].[Load_Adi_All](
    @LoadDate Date
)
AS 
 -- Move data from ast to ADI. 
   -- 1. insert all data values
   -- 2. replace stg Seq_ID with new permanant SKey
   -- 3. Add Load data to indentify load batch.
   -- 4. Need: add logging stuff.


INSERT INTO [adi].[OKC_Claims]
           ([ICN]
           ,[SAK_RECIP]
           ,[Patient_Status]
           ,[Type_Of_Bill]
           ,[Paid_Date]
           ,[DRG_Code]
           ,[Claim_Type]
           ,[SrcFileName]
           ,[LoadDate]
           ,[CreatedDate])
    SELECT 
        [ICN]
          ,[SAK_RECIP]
          ,[Patient_Status]
          ,[Type_Of_Bill]
          ,[Paid_Date]
          ,[DRG_Code]
          ,[Claim_Type]
          ,[FileName]
		,@LoadDate 
          ,[CreatedDate]		
      FROM [ast].[OKC_STG_Claims]
	 where filename <> 'altus_claims_201807_201809.txt';
	 ;
	 
    INSERT INTO [adi].[OKC_Eligibility]
           ([SAK_RECIP]
           ,[Eligibility_Code]
           ,[Eligibility_Effective_Date]
           ,[Eligibility_End_Date]
           ,[Aid_Category]
           ,[Aid_Category_Effective_Date]
           ,[Aid_Category_End_Date]
           ,[SrcFileName]
           ,[LoadDate]
           ,[CreatedDate]
           )
    SELECT [SAK_RECIP]
          ,[Eligibility_Code]
          ,[Eligibility_Effective_Date]
          ,[Eligibility_End_Date]
          ,[Aid_Category]
          ,[Aid_Category_Effective_Date]
          ,[Aid_Category_End_Date]
          ,[fileName]
		, @LoadDate
          ,[createdDate]		
      FROM [ast].[OKC_STG_Eligibility];
	 ;
    

    INSERT INTO [adi].[OKC_ICD9_Diagnosis]
           ([ICN]
           ,[Diagnosis_Sequence]
           ,[SAK_RECIP]
           ,[ICD9_Diagnosis_Code]
           ,[ICD_Version]
           ,[SrcFileName]
           ,[LoadDate]
           ,[CreatedDate]
           )
    SELECT [ICN]
          ,[Diagnosis_Sequence]
          ,[SAK_RECIP]
          ,[ICD9_Diagnosis_Code]
          ,[ICD_Version]
		,[fileName]
		,@LoadDate
          ,[createdDate]
      FROM [ast].[OKC_STG_ICD9_Diagnosis]
	 ;

    INSERT INTO [adi].[OKC_ICD9_Procedure]
           ([ICN]
           ,[ICD_Version]
           ,[SAK_RECIP]
           ,[ICD9_Procedure_Code]
           ,[Procedure_Sequence]
           ,[SrcFileName]
           ,[LoadDate]
           ,[CreatedDate]
           )
     SELECT [ICN]
          ,[ICD_Version]
          ,[SAK_RECIP]
          ,[ICD9_Procedure_Code]
          ,[Procedure_Sequence]
		, [fileName]
		, @LoadDate
          ,[createdDate]
      FROM [ast].[OKC_STG_ICD9_Procedure]
	 ;

    INSERT INTO [adi].[OKC_PcmhAssign]
           ([Provider_ID]
           ,[SAK_RECIP]
           ,[Sooner_Care_Program]
           ,[Sooner_Care_Effective_Date]
           ,[Sooner_Care_End_Date]
           ,[SrcFileName]
           ,[LoadDate]
           ,[CreatedDate]
           )
    SELECT [Provider_ID]
          ,[SAK_RECIP]
          ,[Sooner_Care_Program]
          ,[Sooner_Care_Effective_Date]
          ,[Sooner_Care_End_Date]
		,[fileName]
		, @LoadDate
          ,[createddate]    
      FROM [ast].[OKC_STG_PCMH_Assign]
	 ;

    INSERT INTO [adi].[OKC_PcmhRates]
           ([Provider_ID]
           ,[MH_Rate_Category]
           ,[Payment_Tier_Code]
           ,[Rate_Cell_Age_Group]
           ,[Rate_Cell_Code]
           ,[Rate_Cell_Effective_Date]
           ,[Rate_Cell_End_Date]
           ,[Rate_Cell_Type]
           ,[SrcFileName]
           ,[LoadDate]
           ,[CreatedDate]
           )
     SELECT [Provider_ID]      
          ,[MH_Rate_Category]
          ,[Payment_Tier_Code]
          ,[Rate_Cell_Age_Group]
          ,[Rate_Cell_Code]
          ,[Rate_Cell_Effective_Date]
          ,[Rate_Cell_End_Date]
          ,[Rate_Cell_Type]
          ,[fileName]
		,@LoadDate as LoadDate
          ,[createddate]
      FROM [ast].[OKC_STG_PCMH_Rates]
	 ;

    INSERT INTO [adi].[OKC_Prescriptions]
           ([ICN]
           ,[Detail_Number]
           ,[SAK_RECIP]
           ,[Dispensed_Date]
           ,[NDC_Code]
           ,[Prescriber_ID]
           ,[Dispensed_Qty]
           ,[Days_Supply]
           ,[Billed_Amount]
           ,[Allowed_Amount]
           ,[Paid_Amount]
           ,[Claim_Indicator]
           ,[Paid_Date]
           ,[Pharmacy_ID]
           ,[State_Category_of_Service]
           ,[Health_Program_Code]
           ,[Fund_code]
           ,[SrcFileName]
           ,[LoadDate]
           ,[CreatedDate]
           )
    SELECT [ICN]
          ,[Detail_Number]
          ,[SAK_RECIP]
          ,[Dispensed_Date]
          ,[NDC_Code]
          ,[Prescriber_ID]
          ,[Dispensed_Qty]
          ,[Days_Supply]
          ,[Billed_Amount]
          ,[Allowed_Amount]
          ,[Paid_Amount]
          ,[Claim_Indicator]
          ,[Paid_Date]
          ,[Pharmacy_ID]
          ,[State_Category_of_Service]
          ,[Health_Program_Code]
          ,[Fund_code]
		,[fileName]
		,@LoadDate as LoadDate
		,[createddate]      
    FROM [ast].[OKC_STG_Prescriptions]
    ;

    INSERT INTO [adi].[OKC_ProviderInfo]
           ([Provider_ID]
           ,[Billing_Provider_NPI]
           ,[Provider_Type]
           ,[Zip]
           ,[Specialty_Primary]
           ,[Tax_ID]
           ,[FEIN_SSN_Indicator]
           ,[start_date]
           ,[end_date]
           ,[SrcFileName]
           ,[LoadDate]
           ,[CreatedDate]
           )
    SELECT [Provider_ID]          
          ,[Billing_Provider_NPI]
          ,[Provider_Type]
          ,[Zip]
          ,[Specialty_Primary]
          ,[Tax_ID]
          ,[FEIN_SSN_Indicator]
          ,[start_date]
          ,[end_date]
		,[fileName]
		,@LoadDate as LoadDate
		,[createddate]
      FROM [ast].[OKC_STG_Provider_Info]
	 ;
    
    INSERT INTO [adi].[OKC_RecipientInfo]
           ([SAK_RECIP]
           ,[Date_of_Birth]
           ,[Gender]
           ,[Zip]
           ,[Race_Code]
           ,[Ethnic_Code]
           ,[Tribal_Verification_Description]
           ,[Valid_ID_Indicator]
           ,[SrcFileName]
           ,[LoadDate]
           ,[CreatedDate]
		  )
    SELECT [SAK_RECIP]
          ,[Date_of_Birth]
          ,[Gender]
          ,[Zip]
          ,[Race_Code]
          ,[Ethnic_Code]
          ,[Tribal_Verification_Description]
          ,[Valid_ID_Indicator]
          ,[FileName]
		,@LoadDate AS LoadDate
          ,[CreatedDate]
      FROM [ast].[OKC_STG_Recipient_Info]
	 ;

    INSERT INTO [adi].[OKC_Services]
           ([ICN]
           ,[Detail_Number]
           ,[SAK_RECIP]
           ,[Procedure_Code]
           ,[Procedure_Code_Modifier]
           ,[Revenue_Code]
           ,[Provider_ID]
           ,[Place_Of_Service]
           ,[First_Date_Of_Service]
           ,[Last_Date_Of_Service]
           ,[Billed_Amount]
           ,[Allowed_Amount]
           ,[Paid_Amount]
           ,[Claim_Indicator]
           ,[Paid_Date]
           ,[State_Category_of_Service]
           ,[Health_Program_Code]
           ,[Fund_Code]
           ,[SrcFileName]
           ,[LoadDate]
           ,[CreatedDate]
           )
    SELECT [ICN]
          ,[Detail_Number]
          ,[SAK_RECIP]
          ,[Procedure_Code]
          ,[Procedure_Code_Modifier]
          ,[Revenue_Code]
          ,[Provider_ID]
          ,[Place_Of_Service]
          ,[First_Date_Of_Service]
          ,[Last_Date_Of_Service]
          ,[Billed_Amount]
          ,[Allowed_Amount]
          ,[Paid_Amount]
          ,[Claim_Indicator]
          ,[Paid_Date]
          ,[State_Category_of_Service]
          ,[Health_Program_Code]
          ,[Fund_Code]
          ,[FileName]
		,@LoadDate AS LOADDATE
          ,[CreatedDate]
      FROM [ast].[OKC_STG_Services]
   ; 

   
   --EXEC  [ast].[OkcCleanStaging]
