CREATE TABLE [lst].[LIST_ICDCCS] (
    [ICD-10-CM_CODE]             VARCHAR (500) NULL,
    [CCS_CATEGORY]               VARCHAR (500) NULL,
    [ICD-10-CM_CODE_DESCRIPTION] VARCHAR (500) NULL,
    [CCS_CATEGORY_DESCRIPTION]   VARCHAR (500) NULL,
    [MULTI_CCS_LVL1]             VARCHAR (500) NULL,
    [MULTI_CCS_LVL1_LABEL]       VARCHAR (500) NULL,
    [MULTI_CCS_LVL2]             VARCHAR (500) NULL,
    [MULTI_CCS_LVL2_LABEL]       VARCHAR (500) NULL,
    [MULTI_CCS_LVL3]             VARCHAR (500) NULL,
    [MULTI_CCS_LVL3_LABEL]       VARCHAR (500) NULL,
    [MULTI_CCS_LVL4]             VARCHAR (500) NULL,
    [MULTI_CCS_LVL4_LABEL]       VARCHAR (500) NULL,
    [Version]                    VARCHAR (50)  NULL
);


GO
CREATE NONCLUSTERED INDEX [dboList_ICDCSS_CODE]
    ON [lst].[LIST_ICDCCS]([ICD-10-CM_CODE] ASC);

