CREATE TABLE [lst].[LIST_HEDIS_MEASURE] (
    [MEASURE_ID]         VARCHAR (5)   NULL,
    [MEASURE_NAME]       VARCHAR (255) NULL,
    [VALUE_SET_NAME]     VARCHAR (100) NULL,
    [VALUE_SET_OID]      VARCHAR (100) NULL,
    [A_LAST_UPDATE_DATE] DATETIME      DEFAULT (getdate()) NULL,
    [A_LAST_UPDATE_BY]   VARCHAR (20)  DEFAULT ('HEDIS Vol2 10032016') NULL,
    [A_LAST_UPDATE_FLAG] VARCHAR (1)   DEFAULT ('Y') NULL
);

