CREATE LOGIN [BoomiDbUser]
    WITH PASSWORD = N'jmdAobwzaawb uS{mhyhhxowmsFT7_&#$!~<uBcj:iaGl_y^', SID = 0x7E67B75D90431B40AE3CE7552C81A3D5, DEFAULT_DATABASE = [ACDW_CLMS_WLC_ECAP], DEFAULT_LANGUAGE = [us_english], CHECK_POLICY = OFF;

