
/****** Script for SelectTopNRows command from SSMS  ******/

CREATE VIEW adw.[z_vw_active_members]
AS
     SELECT [URN], 
            [MBI], 
            [HICN], 
            [FirstName], 
            [LastName], 
            [Sex], 
            [DOB], 
            [DOD], 
            [CountyName], 
            [StateName], 
            [CountyNumber], 
            [VoluntaryFlag], 
            [CBFlag], 
            [CBStepFlag], 
            [PrevBenFlag], 
            [HCC1], 
            [HCC2], 
            [HCC6], 
            [HCC8], 
            [HCC9], 
            [HCC10], 
            [HCC11], 
            [HCC12], 
            [HCC17 ], 
            [HCC18 ], 
            [HCC19 ], 
            [HCC21 ], 
            [HCC22 ], 
            [HCC23 ], 
            [HCC27 ], 
            [HCC28 ], 
            [HCC29 ], 
            [HCC33 ], 
            [HCC34 ], 
            [HCC35 ], 
            [HCC39 ], 
            [HCC40 ], 
            [HCC46 ], 
            [HCC47 ], 
            [HCC48 ], 
            [HCC54 ], 
            [HCC55 ], 
            [HCC57 ], 
            [HCC58 ], 
            [HCC70 ], 
            [HCC71 ], 
            [HCC72 ], 
            [HCC73 ], 
            [HCC74 ], 
            [HCC75 ], 
            [HCC76 ], 
            [HCC77 ], 
            [HCC78 ], 
            [HCC79 ], 
            [HCC80 ], 
            [HCC82 ], 
            [HCC83 ], 
            [HCC84 ], 
            [HCC85 ], 
            [HCC86 ], 
            [HCC87 ], 
            [HCC88 ], 
            [HCC96 ], 
            [HCC99 ], 
            [HCC100 ], 
            [HCC103 ], 
            [HCC104 ], 
            [HCC106 ], 
            [HCC107 ], 
            [HCC108 ], 
            [HCC110 ], 
            [HCC111 ], 
            [HCC112 ], 
            [HCC114 ], 
            [HCC115 ], 
            [HCC122 ], 
            [HCC124 ], 
            [HCC134 ], 
            [HCC135 ], 
            [HCC136 ], 
            [HCC137 ], 
            [HCC157 ], 
            [HCC158 ], 
            [HCC161 ], 
            [HCC162 ], 
            [HCC166 ], 
            [HCC167 ], 
            [HCC169 ], 
            [HCC170 ], 
            [HCC173 ], 
            [HCC176 ], 
            [HCC186 ], 
            [HCC188 ], 
            [HCC189 ], 
            [PartDFlag], 
            [RS_ESRD], 
            [RS_Disabled], 
            [RS_AgedDual], 
            [RS_AgedNonDual], 
            [Demo_RS_ESRD], 
            [Demo_RS_Disabled], 
            [Demo_RS_AgedDual], 
            [Demo_RS_AgedNonDual], 
            [ESRD_RS], 
            [DISABLED_RS], 
            [DUAL_RS], 
            [NONDUAL_RS], 
            [ELIG_TYPE], 
            [MBR_YEAR], 
            [MBR_QTR], 
            [LOAD_DATE], 
            [LOAD_USER]
     FROM adw.[Member_History] a
     WHERE a.MBR_YEAR =
     (
         SELECT MAX(MBR_YEAR) AS Expr1
         FROM adw.[Member_History]
     )
           AND a.MBR_QTR =
     (
         SELECT MAX(MBR_QTR) AS Expr1
         FROM adw.[Member_History]
         WHERE MBR_YEAR =
         (
             SELECT MAX(MBR_YEAR)
             FROM adw.[Member_History]
         )
     );
