CREATE TABLE [dbo].[tmp_UTIL_TOTAL_BILLED] (
    [SEQ_CLAIM_ID]     VARCHAR (100) NULL,
    [PRIMARY_SVC_DATE] DATE          NULL,
    [hicn]             VARCHAR (100) NULL,
    [TOTAL_BILLED_AMT] FLOAT (53)    NULL
);

