CREATE TABLE [adw].[Member_History] (
    [URN]                 INT            IDENTITY (1, 1) NOT NULL,
    [MBI]                 VARCHAR (50)   NULL,
    [HICN]                VARCHAR (50)   NULL,
    [Plan]                VARCHAR (50)   NULL,
    [SubPlan]             VARCHAR (100)  NULL,
    [FirstName]           VARCHAR (50)   NULL,
    [LastName]            VARCHAR (50)   NULL,
    [Sex]                 VARCHAR (5)    NULL,
    [DOB]                 DATE           NULL,
    [DOD]                 DATE           NULL,
    [CountyName]          VARCHAR (50)   NULL,
    [StateName]           VARCHAR (25)   NULL,
    [CountyNumber]        VARCHAR (10)   NULL,
    [VoluntaryFlag]       VARCHAR (1)    NULL,
    [CBFlag]              VARCHAR (1)    NULL,
    [CBStepFlag]          VARCHAR (1)    NULL,
    [PrevBenFlag]         VARCHAR (1)    NULL,
    [HCC1]                VARCHAR (1)    NULL,
    [HCC2]                VARCHAR (1)    NULL,
    [HCC6]                VARCHAR (1)    NULL,
    [HCC8]                VARCHAR (1)    NULL,
    [HCC9]                VARCHAR (1)    NULL,
    [HCC10]               VARCHAR (1)    NULL,
    [HCC11]               VARCHAR (1)    NULL,
    [HCC12]               VARCHAR (1)    NULL,
    [HCC17 ]              VARCHAR (1)    NULL,
    [HCC18 ]              VARCHAR (1)    NULL,
    [HCC19 ]              VARCHAR (1)    NULL,
    [HCC21 ]              VARCHAR (1)    NULL,
    [HCC22 ]              VARCHAR (1)    NULL,
    [HCC23 ]              VARCHAR (1)    NULL,
    [HCC27 ]              VARCHAR (1)    NULL,
    [HCC28 ]              VARCHAR (1)    NULL,
    [HCC29 ]              VARCHAR (1)    NULL,
    [HCC33 ]              VARCHAR (1)    NULL,
    [HCC34 ]              VARCHAR (1)    NULL,
    [HCC35 ]              VARCHAR (1)    NULL,
    [HCC39 ]              VARCHAR (1)    NULL,
    [HCC40 ]              VARCHAR (1)    NULL,
    [HCC46 ]              VARCHAR (1)    NULL,
    [HCC47 ]              VARCHAR (1)    NULL,
    [HCC48 ]              VARCHAR (1)    NULL,
    [HCC54 ]              VARCHAR (1)    NULL,
    [HCC55 ]              VARCHAR (1)    NULL,
    [HCC57 ]              VARCHAR (1)    NULL,
    [HCC58 ]              VARCHAR (1)    NULL,
    [HCC70 ]              VARCHAR (1)    NULL,
    [HCC71 ]              VARCHAR (1)    NULL,
    [HCC72 ]              VARCHAR (1)    NULL,
    [HCC73 ]              VARCHAR (1)    NULL,
    [HCC74 ]              VARCHAR (1)    NULL,
    [HCC75 ]              VARCHAR (1)    NULL,
    [HCC76 ]              VARCHAR (1)    NULL,
    [HCC77 ]              VARCHAR (1)    NULL,
    [HCC78 ]              VARCHAR (1)    NULL,
    [HCC79 ]              VARCHAR (1)    NULL,
    [HCC80 ]              VARCHAR (1)    NULL,
    [HCC82 ]              VARCHAR (1)    NULL,
    [HCC83 ]              VARCHAR (1)    NULL,
    [HCC84 ]              VARCHAR (1)    NULL,
    [HCC85 ]              VARCHAR (1)    NULL,
    [HCC86 ]              VARCHAR (1)    NULL,
    [HCC87 ]              VARCHAR (1)    NULL,
    [HCC88 ]              VARCHAR (1)    NULL,
    [HCC96 ]              VARCHAR (1)    NULL,
    [HCC99 ]              VARCHAR (1)    NULL,
    [HCC100 ]             VARCHAR (1)    NULL,
    [HCC103 ]             VARCHAR (1)    NULL,
    [HCC104 ]             VARCHAR (1)    NULL,
    [HCC106 ]             VARCHAR (1)    NULL,
    [HCC107 ]             VARCHAR (1)    NULL,
    [HCC108 ]             VARCHAR (1)    NULL,
    [HCC110 ]             VARCHAR (1)    NULL,
    [HCC111 ]             VARCHAR (1)    NULL,
    [HCC112 ]             VARCHAR (1)    NULL,
    [HCC114 ]             VARCHAR (1)    NULL,
    [HCC115 ]             VARCHAR (1)    NULL,
    [HCC122 ]             VARCHAR (1)    NULL,
    [HCC124 ]             VARCHAR (1)    NULL,
    [HCC134 ]             VARCHAR (1)    NULL,
    [HCC135 ]             VARCHAR (1)    NULL,
    [HCC136 ]             VARCHAR (1)    NULL,
    [HCC137 ]             VARCHAR (1)    NULL,
    [HCC157 ]             VARCHAR (1)    NULL,
    [HCC158 ]             VARCHAR (1)    NULL,
    [HCC161 ]             VARCHAR (1)    NULL,
    [HCC162 ]             VARCHAR (1)    NULL,
    [HCC166 ]             VARCHAR (1)    NULL,
    [HCC167 ]             VARCHAR (1)    NULL,
    [HCC169 ]             VARCHAR (1)    NULL,
    [HCC170 ]             VARCHAR (1)    NULL,
    [HCC173 ]             VARCHAR (1)    NULL,
    [HCC176 ]             VARCHAR (1)    NULL,
    [HCC186 ]             VARCHAR (1)    NULL,
    [HCC188 ]             VARCHAR (1)    NULL,
    [HCC189 ]             VARCHAR (1)    NULL,
    [PartDFlag]           VARCHAR (1)    NULL,
    [RS_ESRD]             DECIMAL (5, 4) NULL,
    [RS_Disabled]         DECIMAL (5, 4) NULL,
    [RS_AgedDual]         DECIMAL (5, 4) NULL,
    [RS_AgedNonDual]      DECIMAL (5, 4) NULL,
    [Demo_RS_ESRD]        DECIMAL (5, 4) NULL,
    [Demo_RS_Disabled]    DECIMAL (5, 4) NULL,
    [Demo_RS_AgedDual]    DECIMAL (5, 4) NULL,
    [Demo_RS_AgedNonDual] DECIMAL (5, 4) NULL,
    [ESRD_RS]             DECIMAL (5, 4) NULL,
    [DISABLED_RS]         DECIMAL (5, 4) NULL,
    [DUAL_RS]             DECIMAL (5, 4) NULL,
    [NONDUAL_RS]          DECIMAL (5, 4) NULL,
    [ELIG_TYPE]           VARCHAR (1)    NULL,
    [MBR_YEAR]            INT            NULL,
    [MBR_QTR]             INT            NULL,
    [LOAD_DATE]           DATE           DEFAULT (sysdatetime()) NULL,
    [LOAD_USER]           VARCHAR (50)   DEFAULT (suser_sname()) NULL,
    PRIMARY KEY CLUSTERED ([URN] ASC)
);


GO
CREATE NONCLUSTERED INDEX [_dta_index_MBR_QTR(HICN)(MBR_YEAR)]
    ON [adw].[Member_History]([MBR_QTR] ASC, [HICN] ASC, [MBR_YEAR] ASC);


GO
CREATE STATISTICS [_dta_stat_MbrQtrMbrYr]
    ON [adw].[Member_History]([MBR_QTR], [MBR_YEAR]);


GO
CREATE STATISTICS [_dta_stat_HicnMbrQtrMbrYr]
    ON [adw].[Member_History]([HICN], [MBR_QTR], [MBR_YEAR]);

